### ISSUE TITLE
Reassigning require to esm causes downstream breakages

### ISSUE THREAD

**Issue by nikolaswise** [digitalbazaar/http-client#19]
I'm trying to use jsonld.js in a verc severless function, but the dependency on this package and its use of esm in not compatible with static analysis used to create the lambda function. 

Since esmodules are supported now in node 14, it would be great to remove this.

**Comment by dlongley** [comment]
Related to #18.

**Comment by nikolaswise** [comment]
@aljones15 I wish I was calling it directly! I'll open a PR now.

@dlongley Is there a model you're following for de-esm-ing these packages? For example, would it be better to move `main.js` to `index.js` and leave the whole thing as an es module, or leave index as it is and just remove the re-assignment to `require` ?

**Comment by nikolaswise** [comment]
Gave this a shot here, but I don't think I managed it in the most graceful manner.

**Comment by dlongley** [comment]
@nikolaswise,

> Is there a model you're following for de-esm-ing these packages?

We're looking at using the conditional exports mechanism:

https://nodejs.org/docs/latest-v14.x/api/packages.html#packages_conditional_exports

Where the module is ESM internally and a legacy CommonJS translation is built at CI / package release time.

We would just have a separate `/dist/commonjs/*` directory that has an entry point there. We'd move the ESM `main.js` back to `index.js` as the modern ESM entry point.

**Comment by dlongley** [comment]
Resolved in version 3.x (via PR #21).
