### ISSUE TITLE
ky-universal again

### ISSUE THREAD

**Issue by musicEnfanthen** [digitalbazaar/http-client#31]
Hi there,

there is a severity vulnerability from latest @digitalbazaar/http-client 3.2.0.
The reason for this vulnerability is because it uses ky-universal 0.10.1 as a dependency, which uses node-fetch@3.2.6. And node-fetch@3.2.6 causes https://github.com/advisories/GHSA-vp56-6g26-6827.
It seems that upgrading to the latest ky-universal (0.11.0) will solve this issue.
Thanks

Cf. #18

**Comment by davidlehn** [comment]
I think this should be addressed in 3.3.0.

**Comment by musicEnfanthen** [comment]
Thanks for the fix! Any chance that this new version will be used by jsonld.js as well?

**Comment by davidlehn** [comment]
It's a minor semver release, so a fresh install of projects that use jsonld.js will probably pull it in.  If needed we can bump the dependency explicitly.

**Comment by musicEnfanthen** [comment]
Yes, it did. Thanks a lot!
