### ISSUE TITLE
Using older node than ^10.17.0, fails

### ISSUE THREAD

**Issue by vongohren** [digitalbazaar/http-client#7]
Im running 12.8 now which is quite stable, but it fails for this library.

![image](https://user-images.githubusercontent.com/1012055/113484294-ca55c500-94a7-11eb-94b2-bd3f01f511ed.png)

There has been some updates to ky and ky-universal to use updated versions of the child libs: https://github.com/sindresorhus/ky-universal

How do you guys want to go about this?

**Comment by vongohren** [comment]
Closing as it is jsonld that is messing around

**Comment by vongohren** [comment]
Acctually it was yarn messing around, meaning yarn fails this install but npm manages to handle it. Strange

**Comment by davidlehn** [comment]
There is a PR that updates to the pre-ESM dependencies that might help with this:
https://github.com/digitalbazaar/http-client/pull/6
